### PR TITLE
Issue 140

### LINKED ISSUE #140: dython.nominal.associations handling fillna with dtype="category"
When the default strategy 'replace' is selected, `associations` raises the following `TypeError: Cannot setitem on a Categorical with a new category (0.0), set the categories first` if the input dataset is a Pandas DataFrame with some columns with dtype="category".

See code below.

```{python}
from dython.nominal import associations
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "A": ["a", "b", "c", "a", np.nan],
    "B": [0.0, 2.0, 1.0, 0.5, np.nan]
})

associations(df) # no expection
df["A"] = df["A"].astype("category")
associations(df) # raise expection
df["A"] = df["A"].cat.add_categories(0.0)
associations(df) # no expection
```

The problem is related to pandas fillna behaviour, see [this](https://stackoverflow.com/questions/53664948/pandas-fillna-throws-valueerror-fill-value-must-be-in-categories) stackoverflow question.

Given that the default strategy 'replace' with value `0.0`, I'm wondering if this case can be handled internally by the  `associations` method or if this is a corner case. Often, the `category` dtype is used when memory efficiency is important and switching dtype is expensive.

### PR DESCRIPTION
**Pull request by enrir**
Hi,
This should fix #140.
The function `handling_category_for_nan_imputation` takes care of columns with category dtypes before nan imputation.
It works works if  `nan_replace_value` is a scalar, dict or DataFrame (most of the values accepted by [pandas.DataFrame.fillna](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html), see script below.

```python
from dython.nominal import associations
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "A": ["a", "b", "c", "a", np.nan],
    "B": [0.0, 2.0, 1.0, 0.5, np.nan]
})
df["A"] = df["A"].astype("category")

associations(df, compute_only=True)
associations(df, compute_only=True, nan_replace_value=pd.DataFrame({
    "A": ["a", "b", "c", "a", "missing"],
    "B": [0.0, 2.0, 1.0, 0.3, 0.0]
})    )
associations(df, compute_only=True, nan_replace_value={
    "A": "missing",
    "B": 0.0
})  

```

### CODE REVIEW

**Comment by shakedzy** [comment]
hey @enrir - it seems like tests fail

**Comment by enrir** [comment]
> hey @enrir - it seems like tests fail

hi @shakedzy, I'm sorry. The fails could be related to #139. I have updated the `requirements.txt`.

**Comment by enrir** [comment]
hey @shakedzy, I was wondering which is the best way to test for this edge case.

For now, I came with two possible solution, let me know if you have any opinion on them.

### 1
```python
import pytest
import matplotlib
import pandas as pd
import numpy as np
import scipy.stats as ss
from sklearn import datasets
from datetime import datetime, timedelta
from contextlib import nullcontext as does_not_raise

from dython.nominal import associations

def test_replace_category(iris_df):
    iris_df["extra"] = iris_df["extra"].astype("category")
    iris_df.loc[5, "extra"] = np.nan
    try:
        associations(iris_df, nan_strategy="replace")
    except TypeError as exception:
        assert False, f"nan_strategy='replace' with a pandas.CategoricalDtype column raised an exception {exception}"
```

or

### 2
```python
def test_replace_category(iris_df):
    with does_not_raise():
        iris_df["extra"] = iris_df["extra"].astype("category")
        iris_df.loc[5, "extra"] = np.nan
        associations(iris_df, nan_strategy="replace")
```

**Comment by shakedzy** [comment]
Hey @enrir - I believe the first will be more readable in the logs if it breaks, so I tend to go with it. What do you think?

**Comment by enrir** [comment]
> Hey @enrir - I believe the first will be more readable in the logs if it breaks, so I tend to go with it. What do you think?

Yes I agree. the first test is also more specific. I have pushed a commit that implemets the test and a second one that should also close #139.

**Review by shakedzy — APPROVED** [review]

**Pull request merged**
