### PR TITLE
"requirements.txt" was not getting picked during packaging

### PR DESCRIPTION
**Pull request by sarthakpati**
Could you verify that both these files are present in the sdist? "requirements.txt" wasn't there in https://files.pythonhosted.org/packages/f5/4c/f57012a4636194a17e94e124f9fa79e18f661db597c18f64a4910d38d134/dython-0.7.1.post2.tar.gz

### CODE REVIEW

**Comment by shakedzy** [comment]
@sarthakpati I'm not sure I understand the issue anymore..

**Comment by sarthakpati** [comment]
Hey @shakedzy, yeah, I think there seems to be something weird going on with the MANIFEST file. Let me see if I can explain it.

- v0.7.1 auto-updated on conda showed there was a build issue [[ref](https://github.com/conda-forge/dython-feedstock/pull/7#issuecomment-1072907945)] where `requirements.txt` was not found [[ref](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=477378&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=140)]
- To solve this, I put in #123, thinking that there would only be a single `requirements` file referred during build, but that was clearly a fallacy on my part, as evidenced by #124
- Anyway, since I didn't do the local build to test (again, a mistake on my part), I figured that would be enough. But apparently, only the last "dev_requirements.txt" got pulled.
- So, with this merge, I did the local build to confirm if both the requirement files are getting picked, and I can confirm that they are:
```bash
(venv_dython) sarthakpati@cbica-bakas-pc06:/mnt/c/Projects/dython$ python setup.py bdist_wheel sdist
(venv_dython) sarthakpati@cbica-bakas-pc06:/mnt/c/Projects/dython$ tar -xvf ./dist/dython-0.7.1.post2.tar.gz 
dython-0.7.1.post2/
dython-0.7.1.post2/CHANGELOG.md
dython-0.7.1.post2/CODE_OF_CONDUCT.md
dython-0.7.1.post2/CONTRIBUTING.md
dython-0.7.1.post2/LICENSE
dython-0.7.1.post2/MANIFEST.in
dython-0.7.1.post2/PKG-INFO
dython-0.7.1.post2/README.md
dython-0.7.1.post2/VERSION
dython-0.7.1.post2/dev_requirements.txt
dython-0.7.1.post2/dython/
dython-0.7.1.post2/dython/__init__.py
dython-0.7.1.post2/dython/_private.py
dython-0.7.1.post2/dython/data_utils.py
dython-0.7.1.post2/dython/examples.py
dython-0.7.1.post2/dython/model_utils.py
dython-0.7.1.post2/dython/nominal.py
dython-0.7.1.post2/dython/sampling.py
dython-0.7.1.post2/dython.egg-info/
dython-0.7.1.post2/dython.egg-info/PKG-INFO
dython-0.7.1.post2/dython.egg-info/SOURCES.txt
dython-0.7.1.post2/dython.egg-info/dependency_links.txt
dython-0.7.1.post2/dython.egg-info/requires.txt
dython-0.7.1.post2/dython.egg-info/top_level.txt
dython-0.7.1.post2/pyproject.toml
dython-0.7.1.post2/requirements.txt
dython-0.7.1.post2/setup.cfg
dython-0.7.1.post2/setup.py
(venv_dython) sarthakpati@cbica-bakas-pc06:/mnt/c/Projects/dython$ ls dython-0.7.1.post2/*.txt
dython-0.7.1.post2/dev_requirements.txt  dython-0.7.1.post2/requirements.txt
```
- So, merging this PR and pushing a new version should fix the conda builds!

Once again, thank you so much for your patience with this. Conda is very finnicky with builds and needs every single file referenced in `setup.py` to be present in the sdist pushed to pip...

**Comment by shakedzy** [comment]
@sarthakpati is it working now?

**Comment by sarthakpati** [comment]
> @sarthakpati is it working now?

Hey @shakedzy, I am waiting for conda to pick up the new builds... I'll keep you posted, thanks!

**Comment by sarthakpati** [comment]
> > @sarthakpati is it working now?
> 
> Hey @shakedzy, I am waiting for conda to pick up the new builds... I'll keep you posted, thanks!

Yas!!

https://github.com/conda-forge/dython-feedstock/pull/9

**Pull request merged**
