### PR TITLE
identify categorical columns/fix pep8

### PR DESCRIPTION
**Pull request by benman1**
Hi
I really like the correlation functionality. However, I thought it could be easier if there was a functionality to consider categorical, the ones that are either marked categorical (pd.Categorical) or strings. So I've created a flag option, nominal_columns='auto'.

The example can now run like this:
```
import pandas as pd
from sklearn import datasets
from dython.nominal import associations
iris = datasets.load_iris()
X = pd.DataFrame(data=iris.data, columns=iris.feature_names)
y = pd.DataFrame(data=iris.target, columns=['target'])
df = pd.concat([X, y], axis=1)
associations(df, nominal_columns='auto')
```

While looking at the code, I've also fixed some pep8. If you don't like this, ignore the second commit.

Cheers.

### CODE REVIEW

**Comment by shakedzy** [comment]
Super cool! What a great idea :)
Few things left:

- Add a docstring to the new function
- Add the new function the website documentation (`docs/nominal.md`) as this isn't a private function
- bump the version. I think this qualifies for `0.4.0`

I'll do it myself during the upcoming weekend, unless you wish to do it too :)
Great job!

**Comment by benman1** [comment]
Hi again
I have done the suggested fixes plus a lot more for pep8 across all the rest of the files, especially line length. I hope you like the look. 

BTW, do you have more plans for this library?

Cheers
Ben.

**Comment by shakedzy** [comment]
Hi! thanks, I'll go over everything in the next few days. Awesome!
I never had any plans for this.. I'm still surprised people use this :)

**Comment by benman1** [comment]
Thanks! 
It's a useful tool, well done!

**Comment by shakedzy** [comment]
@benman1 I don't understand why you're not listed as a contributor now..

**Comment by benman1** [comment]
@shakedzy I'd be honored to be listed, thank you for suggesting.

**Comment by shakedzy** [comment]
You should have appeared.. I don't understand why you're not. Going through GitHub Help, it might be something to do with your account linking. Or maybe another thing.. Check these out:

- https://stackoverflow.com/questions/40644933/not-showing-as-a-contributor-on-github
- https://help.github.com/enterprise/2.8/user/articles/i-don-t-see-myself-in-the-repository-contributors-graph
- https://help.github.com/en/github/setting-up-and-managing-your-github-profile/why-are-my-contributions-not-showing-up-on-my-profile

**Comment by benman1** [comment]
Thanks for alerting me to this, and for the links - that was helpful. I was using two email addresses. I've entered the second email address, and I am showing up as a contributor now.

**Pull request merged**
