### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by lahdjirayhan**
I am interested in contributing some kind of tests for this package. Are there necessary test cases that come into mind?

I was about to write separate tests, but every test I wrote was eventually just some variation of validating/repeating docstring examples. So far, I merely configured pytest to run doctest, as a starting point for this PR.

### CODE REVIEW

**Comment by shakedzy** [comment]
Hey @lahdjirayhan ! thanks a lot for this :) I think the most important method to test is `associations`, as this is the primary method used in this module. It has several different output options which vary by data, plus it uses several inner methods from `_private` module.

**Comment by lahdjirayhan** [comment]
@shakedzy 

Thank you for your kind response! Please take a look at my proposed tests.

I have questions. `associations` can give different results, depending on passed arguments i.e. `nom_nom_assoc`, `num_num_assoc`, etc. (you even explicitly mentioned this). I'm confused as to how properly make a test that account for this behavior. Do you think the test should be like this?
  - Check if `associations` using `nom_nom_assoc='theil'` returns a specific matrix (or, one identifying element of it) precomputed by hand.
  - Check if `associations` using `nom_nom_assoc='cramer'` returns a specific matrix (or, one identifying element of it) precomputed by hand.
  - and so on, and so forth, for each possible argument values..

Such method was my first thought. My issue with it, however, is that the test of `associations` will grow quickly, each for combinations of inputs. Consequently it will make the test hard to read and maintain (in my humble, novice opinion).

That being said, I feel like my current tests are ... not comprehensive enough?

I'm not sure how to proceed, but I'm eager to contribute further. Again, many thanks. I'm looking forward to seeing where this goes!

**Comment by shakedzy** [comment]
@lahdjirayhan looking good :) thanks!
You are correct - writing tests to all possible options of `associations` is tedious, I haven't really came up with a way to do it in any other way.. would be happy to hear what you think

**Comment by shakedzy** [comment]
Wow, @lahdjirayhan - that's some amazing work! Thanks a lot for your contributions, these are highly appreciated. I see you're on a roll here, let me know when you think you're done so I'll be able to evaluate and merge your final work.

**Comment by lahdjirayhan** [comment]
I have to raise two things that might concern you up front before you start reviewing my work:

1. I change the console indicator from `>>` to `>>>` across the entire package. (I'm using vscode's search and replace feature, verify that it doesn't point to anything other than a console indicator, and then run the replace.) This is necessary so that the docstring examples can be tested, because the doctests module recognizes the latter but not the former. I have also slightly adapted the docstrings so it passes the doctests (as it should be).
2. I purposefully create two tests that the current dython fail to pass:
  - `one_hot_encode` should raise an error when it detects a negative value. I think it's trivial enough to implement and I'm worried people will not read through the documentation -- and maybe even less will follow through to the original SO post -- and just use the function anyway with little care for negative value. It may lead to a hard-to-debug behavior down the line by the user.
  - `one_hot_encode` should raise an error when used on a list containing only single unique value, especially [0, 0, ..., 0, 0]. It occurred to me like "Why would you one-hot-encode single value column? Are you sure nothing is wrong?" However, now that I've pushed the commits, I'm not sure whether that particular behavior is better than the current implementation.
  If you think I should also change the implementation so it passes the above tests, let me know. If you think these tests are unnecessary, also let me know.

---

I think I'm done by now, so you can now start reviewing. I'm really looking forward to seeing my contributions be merged. :)

**Comment by shakedzy** [comment]
Hey @lahdjirayhan - amazing stuff! 
as for `one_hot_encode` - you're absolutely right about the negative values issue, this should raise an exception. As for a single value, I wouldn't raise an exception here. It's probably bad practice or misunderstanding of what one-hot encoding does, but it's not wrong.

**Comment by shakedzy** [comment]
@lahdjirayhan I've added some stuff, and fixed a few others.. let me know if you any thoughts before I merge it :)

**Comment by lahdjirayhan** [comment]
Looks good to me! :) @shakedzy

**Comment by shakedzy** [comment]
Merged :) thanks a lot for your contribution!

**Pull request merged**
