### PR TITLE
optional log base for conditional_entropy

### PR DESCRIPTION
**Pull request by ahmedsalhin**
Covering #35

Summary changes:

1. Add optional argument to specify log base when calculating `conditional_entropy`
2. Default base to e
3. Add base argument to docstring

### CODE REVIEW

**Comment by shakedzy** [comment]
Cool, thanks - but the default can't be 2 now, due to backward-compatibility, so if will have to be `math.e`.

**Comment by ahmedsalhin** [comment]
> Cool, thanks - but the default can't be 2 now, due to backward-compatibility, so if will have to be `math.e`.

How could I miss that. Now fixed 😁

**Comment by shakedzy** [comment]
Thanks a lot!

**Comment by ahmedsalhin** [comment]
> Thanks a lot!

My pleasure, and thank you for making all these efforts. 👍

**Pull request merged**
